# Build Stage
FROM --platform=linux/amd64 ubuntu:20.04 as builder

## Install build dependencies.
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc

ADD . /selfie
WORKDIR /selfie
RUN make

RUN mkdir -p /deps
RUN ldd /selfie/selfie | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:20.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /selfie/selfie /selfie/selfie
ENV LD_LIBRARY_PATH=/deps

