# Build Stage
FROM --platform=linux/amd64 ubuntu:20.04 as builder

## Install build dependencies.
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc

COPY . /selfie
WORKDIR /selfie
RUN make

FROM ubuntu:20.04 as package
COPY --from=builder /selfie/selfie /
